// <auto-generated />
using System;
using FinalProjectIzzy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectIzzy.Migrations
{
    [DbContext(typeof(FinalProjectIzzyContext))]
    [Migration("20251204184522_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectIzzy.Models.DanceMoves", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoveId"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("IdealTempo")
                        .HasColumnType("int");

                    b.Property<string>("MusicType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MoveId");

                    b.ToTable("DanceMoves");

                    b.HasData(
                        new
                        {
                            MoveId = 1,
                            Difficulty = 3,
                            IdealTempo = 95,
                            MusicType = "Urban Beat",
                            Style = "Hip Hop"
                        },
                        new
                        {
                            MoveId = 2,
                            Difficulty = 4,
                            IdealTempo = 180,
                            MusicType = "Latin",
                            Style = "Salsa"
                        });
                });

            modelBuilder.Entity("FinalProjectIzzy.Models.NatureTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrailLength")
                        .HasColumnType("float");

                    b.Property<string>("TrailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WildLifeSightings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NatureTrail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyLevel = "Moderate",
                            TrailLength = 4.7000000000000002,
                            TrailName = "Pine Ridge Loop",
                            WildLifeSightings = "Deer, red foxes, woodpeckers"
                        },
                        new
                        {
                            Id = 2,
                            DifficultyLevel = "Hard",
                            TrailLength = 9.3000000000000007,
                            TrailName = "Eagle Summit Trail",
                            WildLifeSightings = "Eagles, mountain goats, marmots"
                        });
                });

            modelBuilder.Entity("FinalProjectIzzy.Models.TeamMembers", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            BirthDate = new DateTime(2006, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            MemberName = "Isabelle Peck",
                            YearInProgram = "Third year"
                        },
                        new
                        {
                            MemberId = 2,
                            BirthDate = new DateTime(2006, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            MemberName = "Ethan Zins",
                            YearInProgram = "Second Year"
                        });
                });

            modelBuilder.Entity("FinalProjectIzzy.Models.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGame");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo",
                            Genre = "Action-Adventure",
                            Platform = "Nintendo Switch",
                            ReleaseDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Legend of Zelda: Tears of the Kingdom"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "FromSoftware",
                            Genre = "Action RPG",
                            Platform = "PC / PlayStation / Xbox",
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
